# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/fairphone/FP3/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    modem \
    dsp \
    cmnlib64 \
    cmnlib \
    devcfg \
    aboot \
    keymaster \
    lksecapp \
    mdtp \
    rpm \
    sbl1 \
    tz
